// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxG-nPFPt3V7ISg67GYFPFALxrZqxUWTc',
    appId: '1:793315550168:web:83048282cca7afa80488ad',
    messagingSenderId: '793315550168',
    projectId: 'cointacao',
    authDomain: 'cointacao.firebaseapp.com',
    storageBucket: 'cointacao.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAmsOM9QhVYvBQWE3JsYdLtfxbWs1v1fNg',
    appId: '1:793315550168:android:2bd9724b69b84be60488ad',
    messagingSenderId: '793315550168',
    projectId: 'cointacao',
    storageBucket: 'cointacao.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyApZX4YYQhaZrlT1EVDjo4O5Gnobbv0Ln8',
    appId: '1:793315550168:ios:8dbd0fe1edcf79bd0488ad',
    messagingSenderId: '793315550168',
    projectId: 'cointacao',
    storageBucket: 'cointacao.appspot.com',
    iosBundleId: 'com.example.cointacao',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyApZX4YYQhaZrlT1EVDjo4O5Gnobbv0Ln8',
    appId: '1:793315550168:ios:8dbd0fe1edcf79bd0488ad',
    messagingSenderId: '793315550168',
    projectId: 'cointacao',
    storageBucket: 'cointacao.appspot.com',
    iosBundleId: 'com.example.cointacao',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDxG-nPFPt3V7ISg67GYFPFALxrZqxUWTc',
    appId: '1:793315550168:web:5c01b50e50e06bc30488ad',
    messagingSenderId: '793315550168',
    projectId: 'cointacao',
    authDomain: 'cointacao.firebaseapp.com',
    storageBucket: 'cointacao.appspot.com',
  );
}
